// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOU9yofjuZUbr5OUwlDGrAZqQKOyPAFZ4',
    appId: '1:795539253831:web:9dc0c2cdae3ac6dc449f62',
    messagingSenderId: '795539253831',
    projectId: 'growwcode-31cec',
    authDomain: 'growwcode-31cec.firebaseapp.com',
    databaseURL: 'https://growwcode-31cec-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'growwcode-31cec.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaghjCboLtGwCRNhmkWSUC78LoYb6b5bQ',
    appId: '1:795539253831:android:e3c962a8cf45dcac449f62',
    messagingSenderId: '795539253831',
    projectId: 'growwcode-31cec',
    databaseURL: 'https://growwcode-31cec-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'growwcode-31cec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDglgeokccyNOFROXs98r5OXAcoJXtbgmo',
    appId: '1:795539253831:ios:933c7ddfcb673dab449f62',
    messagingSenderId: '795539253831',
    projectId: 'growwcode-31cec',
    databaseURL: 'https://growwcode-31cec-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'growwcode-31cec.firebasestorage.app',
    iosBundleId: 'com.example.growwcode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDglgeokccyNOFROXs98r5OXAcoJXtbgmo',
    appId: '1:795539253831:ios:933c7ddfcb673dab449f62',
    messagingSenderId: '795539253831',
    projectId: 'growwcode-31cec',
    databaseURL: 'https://growwcode-31cec-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'growwcode-31cec.firebasestorage.app',
    iosBundleId: 'com.example.growwcode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOU9yofjuZUbr5OUwlDGrAZqQKOyPAFZ4',
    appId: '1:795539253831:web:e76ae74e37e2707e449f62',
    messagingSenderId: '795539253831',
    projectId: 'growwcode-31cec',
    authDomain: 'growwcode-31cec.firebaseapp.com',
    databaseURL: 'https://growwcode-31cec-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'growwcode-31cec.firebasestorage.app',
  );

}